---
apiVersion: v1
kind: Secret
metadata:
  name: simpleapp-db-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:Zxcvbnm123@postgres:5432/simpleapp?sslmode=disable"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: simpleapp-migrate
  namespace: default
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: migrate
        image: almuko/simpleapp:latest
        command: ["goose", "-dir", "./migrations", "postgres", "$(DATABASE_URL)", "up"]
        envFrom:
        - secretRef:
            name: simpleapp-db-secret
  backoffLimit: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: almuko/simpleapp:latest
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: simpleapp-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp
  namespace: default
spec:
  selector:
    app: simpleapp
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpleapp-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"   # ⬅️ cert-manager будет выпускать сертификаты
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - simpleapp.compnet.kz
    secretName: simpleapp-tls
  rules:
  - host: simpleapp.compnet.kz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simpleapp
            port:
              number: 80
