---
apiVersion: v1
kind: Secret
metadata:
  name: simpleapp-db-secret
type: Opaque
stringData:
  url: "postgres://myuser:Zxcvbnm123@postgres:5432/simpleapp?sslmode=disable"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: simpleapp-migrate
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
        - name: migrate
          image: almuko/simpleapp:latest
          command: ["sh", "-c", "goose -dir ./migrations postgres \"$DATABASE_URL\" up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: simpleapp-db-secret
                  key: url

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
        - name: app
          image: almuko/simpleapp:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: simpleapp-db-secret
                  key: url

---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp
spec:
  selector:
    app: simpleapp
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simpleapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - simpleapp.compnet.kz
      secretName: simpleapp-tls
  rules:
    - host: simpleapp.compnet.kz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: simpleapp
                port:
                  number: 80
